import { Platform, StyleSheet } from 'react-native';
import { WEB_GAME_TOUCH_STYLE } from '../../utils/webGameTouch';

/** Quest-board fantasy tokens (aligned with QuestHubScreen + Monster Ladder). */
export const RESCUE_COLORS = {
  kicker: '#c28a3a',
  title: '#ffe6a3',
  sub: '#93c5fd',
  body: '#cbd5e1',
  rowTitle: '#f8fafc',
  rowMeta: '#94a3b8',
  chevron: '#fde68a',
  panelBg: 'rgba(15, 22, 42, 0.97)',
  panelBorder: 'rgba(255,224,143,0.9)',
  rowBorder: 'rgba(244,114,182,0.5)',
  rowBg: 'rgba(76, 29, 58, 0.45)',
  badgeBg: '#db2777',
  badgeBorder: '#fbcfe8',
  canvasBorder: 'rgba(255,224,143,0.65)',
  canvasBg: 'rgba(8, 12, 28, 0.55)',
  win: '#86efac',
  lose: '#fca5a5',
  rewardGold: '#fde68a',
};

export const rescueWebShadow =
  Platform.OS === 'web' ? { boxShadow: '0 10px 28px rgba(0,0,0,0.45)' } : {};

export const rescueFrameStyles = StyleSheet.create({
  root: {
    flex: 1,
    minHeight: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#09051a',
  },
  gameFrame: {
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: '#12071d',
    flex: 1,
    width: '100%',
    ...(Platform.OS === 'web'
      ? {
          maxWidth: 'min(100vw, calc(100dvh * 0.667))',
          maxHeight: 'min(100dvh, calc(100vw * 1.5))',
          boxShadow: '0 18px 50px rgba(0,0,0,0.45)',
        }
      : {}),
  },
  backgroundLayer: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  backgroundImage: {
    width: '100%',
    height: '100%',
  },
  uiLayer: {
    flex: 1,
    minHeight: 0,
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 10,
    gap: 8,
  },
});

export const rescueUiStyles = StyleSheet.create({
  navPill: {
    alignSelf: 'flex-start',
    minHeight: 30,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255, 219, 142, 0.55)',
    backgroundColor: 'rgba(22, 8, 38, 0.72)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  navPillText: {
    color: '#ffe7a3',
    fontSize: 12,
    fontWeight: '900',
  },
  headerPanel: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: RESCUE_COLORS.panelBorder,
    backgroundColor: RESCUE_COLORS.panelBg,
    padding: 10,
    gap: 4,
    ...rescueWebShadow,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  titleIcon: { width: 34, height: 34 },
  kicker: {
    color: RESCUE_COLORS.kicker,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  title: {
    color: RESCUE_COLORS.title,
    fontSize: 18,
    fontWeight: '900',
  },
  sub: {
    color: RESCUE_COLORS.sub,
    fontSize: 11,
    fontWeight: '700',
  },
  blurb: {
    color: RESCUE_COLORS.body,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '700',
  },
  saveHint: {
    color: RESCUE_COLORS.sub,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '600',
    marginTop: 8,
  },
  cloudSyncBtn: {
    marginTop: 10,
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 219, 142, 0.45)',
    backgroundColor: 'rgba(40, 20, 60, 0.85)',
  },
  cloudSyncBtnText: {
    color: '#ffe6a3',
    fontSize: 11,
    fontWeight: '800',
  },
  noticeBar: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 219, 142, 0.35)',
    backgroundColor: 'rgba(22, 8, 38, 0.78)',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  noticeText: {
    color: '#e0f2fe',
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'center',
  },
  stageList: {
    flex: 1,
    minHeight: 0,
  },
  stageListContent: {
    gap: 8,
    paddingBottom: 12,
  },
  stageRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 9,
    paddingHorizontal: 9,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: RESCUE_COLORS.rowBorder,
    backgroundColor: RESCUE_COLORS.rowBg,
    ...(Platform.OS === 'web' ? { cursor: 'pointer' } : {}),
  },
  stageLocked: { opacity: 0.48 },
  stageCleared: {
    borderColor: 'rgba(134,239,172,0.55)',
    backgroundColor: 'rgba(20, 60, 45, 0.42)',
  },
  stageBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: RESCUE_COLORS.badgeBg,
    borderWidth: 1,
    borderColor: RESCUE_COLORS.badgeBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stageBadgeText: { color: '#fff', fontWeight: '900', fontSize: 13 },
  stageCopy: { flex: 1, minWidth: 0 },
  stageName: { color: RESCUE_COLORS.rowTitle, fontSize: 13, fontWeight: '900' },
  stageMeta: { color: RESCUE_COLORS.rowMeta, fontSize: 10, lineHeight: 14, marginTop: 2 },
  stageAction: { color: RESCUE_COLORS.chevron, fontSize: 18, fontWeight: '300' },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 219, 142, 0.4)',
    backgroundColor: 'rgba(15, 22, 42, 0.88)',
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  topBarTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '900',
    color: RESCUE_COLORS.title,
  },
  topBarSpacer: { width: 72 },
  canvasFrame: {
    flex: 1,
    minHeight: 280,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: RESCUE_COLORS.canvasBorder,
    backgroundColor: RESCUE_COLORS.canvasBg,
    overflow: 'hidden',
    ...rescueWebShadow,
    ...WEB_GAME_TOUCH_STYLE,
  },
  canvasPlaceholder: {
    flex: 1,
    width: '100%',
    minHeight: 280,
    alignItems: 'center',
    justifyContent: 'center',
  },
  finishOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(8, 12, 28, 0.82)',
    paddingHorizontal: 16,
  },
  finishOverlayText: {
    color: RESCUE_COLORS.title,
    fontWeight: '900',
    fontSize: 14,
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  rewardScroll: {
    flex: 1,
    minHeight: 0,
    width: '100%',
  },
  rewardBody: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    gap: 10,
  },
  chestImg: { width: 72, height: 72 },
  banner: { fontSize: 22, fontWeight: '900', textAlign: 'center' },
  bannerWin: { color: RESCUE_COLORS.win },
  bannerLose: { color: RESCUE_COLORS.lose },
  statsPanel: {
    width: '100%',
    maxWidth: 320,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: RESCUE_COLORS.panelBorder,
    backgroundColor: RESCUE_COLORS.panelBg,
    padding: 14,
    gap: 5,
    ...rescueWebShadow,
  },
  statRow: { color: '#e2e8f0', fontWeight: '600', fontSize: 13 },
  statDivider: { height: 1, backgroundColor: 'rgba(255,255,255,0.12)', marginVertical: 6 },
  statReward: { color: RESCUE_COLORS.rewardGold, fontWeight: '800', fontSize: 15 },
  saveStatus: {
    color: RESCUE_COLORS.sub,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 4,
    marginBottom: 4,
    paddingHorizontal: 8,
  },
  primaryBtn: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#efd17a',
    borderBottomWidth: 5,
    borderBottomColor: '#31551f',
    backgroundColor: 'rgba(48, 129, 66, 0.96)',
    minWidth: 200,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.34,
    shadowRadius: 7,
    elevation: 8,
    ...(Platform.OS === 'web' ? { cursor: 'pointer' } : {}),
  },
  primaryBtnText: {
    color: '#fff6d6',
    fontWeight: '900',
    fontSize: 14,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  secondaryBtn: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 219, 142, 0.45)',
    backgroundColor: 'rgba(22, 8, 38, 0.72)',
    ...(Platform.OS === 'web' ? { cursor: 'pointer' } : {}),
  },
  secondaryBtnText: { color: '#e0f2fe', fontWeight: '800', fontSize: 12 },
});
