export const GAME_ASSETS = {
  homeMainMenu: '/assets/backgrounds/main-menu.png',
  monsterLadderBackground: '/assets/Quest/Monster_Ladder.jpeg',
  battleGrounds: [
    '/assets/BattleGround/BattleGround.png',
    '/assets/BattleGround/Battleground_2.png',
    '/assets/BattleGround/Battleground_3.png',
  ],
  battleActions: {
    attack: '/assets/actions/action_attack.png',
    attack1: '/assets/actions/action_attack1.png',
    attack2: '/assets/actions/action_attack2.png',
    magic: '/assets/actions/action_magic.png',
    magic1: '/assets/actions/action1_magic.png',
    magic2: '/assets/actions/action_magic2.png',
    defend: '/assets/actions/action_defend.png',
    run: '/assets/actions/action_run.png',
    comment: '/assets/actions/action_comment.png',
    attackVariants: [
      '/assets/actions/action_attack.png',
      '/assets/actions/action_attack1.png',
      '/assets/actions/action_attack2.png',
    ],
    magicVariants: [
      '/assets/actions/action_magic.png',
      '/assets/actions/action1_magic.png',
      '/assets/actions/action_magic2.png',
    ],
    feedback: {
      critical: '/assets/actions/feedback_critical.png',
      dodge: '/assets/actions/feedback_dodge.png',
      miss: '/assets/actions/feedback_miss.png',
      guard: '/assets/actions/feedback_guard.png',
      ko: '/assets/actions/feedback_ko.png',
      hit: '/assets/actions/feedback_hit.png',
    },
  },
  chestClosed: '/assets/others/chest_close.png',
  chestOpen: '/assets/others/chest_open.png',
};
