/**
 * Per-monster visual identity — themed SVG body, aura, palette, archetype.
 * `themeBody` selects a silhouette in components/monsters/bodies/.
 */

/** @typedef {'kaiju'|'mech'|'alien'|'hybrid'} MonsterArchetype */
/** @typedef {{ base: string, light: string, dark: string, accent: string, glow: string }} MonsterPalette */

/** @type {Record<string, { emoji: string, aura: string, label: string, colorIdx: number, themeBody: string, archetype: MonsterArchetype, palette: MonsterPalette }>} */
export const MONSTER_THEMES = {
  cockroachsaurus: {
    emoji: '🪳',
    aura: '#8d6e63',
    label: 'Cockroach',
    colorIdx: 5,
    themeBody: 'cockroach',
    archetype: 'kaiju',
    palette: { base: '#6d4c41', light: '#a1887f', dark: '#4e342e', accent: '#bcaaa4', glow: '#d7ccc8' },
  },
  chickenzilla: {
    emoji: '🐔',
    aura: '#ffeaa7',
    label: 'Chicken',
    colorIdx: 3,
    themeBody: 'chicken',
    archetype: 'kaiju',
    palette: { base: '#fff8e8', light: '#fffef5', dark: '#f5d6a8', accent: '#e74c3c', glow: '#f39c12' },
  },
  water_bottle_beast: {
    emoji: '💧',
    aura: '#48cae4',
    label: 'Water bottle',
    colorIdx: 6,
    themeBody: 'water_bottle',
    archetype: 'hybrid',
    palette: { base: '#81d4fa', light: '#e3f7ff', dark: '#4fc3f7', accent: '#0984e3', glow: '#48cae4' },
  },
  crocs_goblin: {
    emoji: '🩴',
    aura: '#00b894',
    label: 'Crocs goblin',
    colorIdx: 6,
    themeBody: 'crocs',
    archetype: 'alien',
    palette: { base: '#00b894', light: '#55efc4', dark: '#00896f', accent: '#ffeaa7', glow: '#81ecec' },
  },
  iphone_warrior: {
    emoji: '📱',
    aura: '#b2bec3',
    label: 'iPhone warrior',
    colorIdx: 4,
    themeBody: 'iphone',
    archetype: 'mech',
    palette: { base: '#636e72', light: '#b2bec3', dark: '#2d3436', accent: '#74b9ff', glow: '#ffd166' },
  },
  lunchbox_dragon: {
    emoji: '🍱',
    aura: '#e17055',
    label: 'Lunchbox',
    colorIdx: 2,
    themeBody: 'lunchbox',
    archetype: 'kaiju',
    palette: { base: '#e17055', light: '#fab1a0', dark: '#c0392b', accent: '#f39c12', glow: '#e74c3c' },
  },
  pencil_shark: {
    emoji: '✏️',
    aura: '#fdcb6e',
    label: 'Pencil shark',
    colorIdx: 1,
    themeBody: 'pencil',
    archetype: 'kaiju',
    palette: { base: '#fdcb6e', light: '#ffeaa7', dark: '#e17055', accent: '#e84393', glow: '#f8c291' },
  },
  homework_troll: {
    emoji: '📚',
    aura: '#6c5ce7',
    label: 'Homework',
    colorIdx: 7,
    themeBody: 'homework',
    archetype: 'alien',
    palette: { base: '#6c5ce7', light: '#a29bfe', dark: '#4834d4', accent: '#fd79a8', glow: '#ffeaa7' },
  },
  toilet_paper_ninja: {
    emoji: '🧻',
    aura: '#ecf0f1',
    label: 'Toilet roll',
    colorIdx: 0,
    themeBody: 'toilet_paper',
    archetype: 'alien',
    palette: { base: '#f5f5f5', light: '#ffffff', dark: '#dfe6e9', accent: '#2d3436', glow: '#b2bec3' },
  },
  schoolbag_golem: {
    emoji: '🎒',
    aura: '#e84393',
    label: 'School bag',
    colorIdx: 4,
    themeBody: 'schoolbag',
    archetype: 'mech',
    palette: { base: '#e84393', light: '#fd79a8', dark: '#c0392b', accent: '#ffd166', glow: '#ff6b6b' },
  },
  t_rex: {
    emoji: '🦖',
    aura: '#27ae60',
    label: 'T-Rex',
    colorIdx: 3,
    themeBody: 'trex',
    archetype: 'kaiju',
    palette: { base: '#27ae60', light: '#58d68d', dark: '#1e8449', accent: '#f39c12', glow: '#2ecc71' },
  },
  tablet_wizard: {
    emoji: '📱',
    aura: '#a29bfe',
    label: 'Tablet wizard',
    colorIdx: 7,
    themeBody: 'tablet',
    archetype: 'hybrid',
    palette: { base: '#a29bfe', light: '#dfe6e9', dark: '#6c5ce7', accent: '#48cae4', glow: '#ffeaa7' },
  },
  skibidi_bot: {
    emoji: '🚽',
    aura: '#636e72',
    label: 'Skibidi bot',
    colorIdx: 5,
    themeBody: 'skibidi',
    archetype: 'mech',
    palette: { base: '#f5f5f5', light: '#ffffff', dark: '#b2bec3', accent: '#ffeaa7', glow: '#4fc3f7' },
  },
  bubble_tea_slime: {
    emoji: '🧋',
    aura: '#ff85e4',
    label: 'Bubble tea',
    colorIdx: 7,
    themeBody: 'bubble_tea',
    archetype: 'alien',
    palette: { base: '#ff85e4', light: '#ffc8f0', dark: '#e84393', accent: '#2d3436', glow: '#fd79a8' },
  },
  sixtyseven_rex: {
    emoji: '67',
    aura: '#fd79a8',
    label: '67 Rex',
    colorIdx: 5,
    themeBody: 'sixtyseven',
    archetype: 'kaiju',
    palette: { base: '#fd79a8', light: '#ffb8d0', dark: '#e84393', accent: '#2d3436', glow: '#ffd166' },
  },
  goldzilla: {
    emoji: '🦖',
    aura: '#f1c40f',
    label: 'Goldzilla',
    colorIdx: 4,
    themeBody: 'sixtyseven',
    archetype: 'kaiju',
    palette: { base: '#f1c40f', light: '#ffeaa7', dark: '#d4ac0d', accent: '#2d3436', glow: '#ffd166' },
  },
  glitchroach_prime: {
    emoji: '🪳',
    aura: '#00f5d4',
    label: 'Cyber roach',
    colorIdx: 6,
    themeBody: 'cockroach',
    archetype: 'alien',
    palette: { base: '#243b53', light: '#4cc9f0', dark: '#102a43', accent: '#80ffdb', glow: '#00f5d4' },
  },
  toiletron_titan: {
    emoji: '🚽',
    aura: '#74c0fc',
    label: 'Toilet mech',
    colorIdx: 0,
    themeBody: 'toiletron',
    archetype: 'mech',
    palette: { base: '#dfe6e9', light: '#ffffff', dark: '#8395a7', accent: '#48cae4', glow: '#00d2ff' },
  },
  nugget_dragon: {
    emoji: '🍗',
    aura: '#ffb703',
    label: 'Nugget dragon',
    colorIdx: 5,
    themeBody: 'nugget_dragon',
    archetype: 'kaiju',
    palette: { base: '#f59f00', light: '#ffd166', dark: '#b85c00', accent: '#e63946', glow: '#ffbe0b' },
  },
  bubble_tea_hydra: {
    emoji: '🧋',
    aura: '#ff85e4',
    label: 'Boba hydra',
    colorIdx: 7,
    themeBody: 'bubble_tea',
    archetype: 'alien',
    palette: { base: '#d77cff', light: '#ffc8f0', dark: '#7b2cbf', accent: '#2d1b12', glow: '#fd79a8' },
  },
  lagzilla: {
    emoji: '⏳',
    aura: '#7c3aed',
    label: 'Glitch kaiju',
    colorIdx: 4,
    themeBody: 'trex',
    archetype: 'kaiju',
    palette: { base: '#5b21b6', light: '#a78bfa', dark: '#1e1b4b', accent: '#22d3ee', glow: '#c084fc' },
  },
  durian_knight: {
    emoji: '🌳',
    aura: '#9acd32',
    label: 'Durian knight',
    colorIdx: 3,
    themeBody: 'durian_knight',
    archetype: 'kaiju',
    palette: { base: '#7cb342', light: '#c0ca33', dark: '#33691e', accent: '#ffd166', glow: '#d4ff4f' },
  },
  wifi_wraith: {
    emoji: '📶',
    aura: '#67e8f9',
    label: 'Signal ghost',
    colorIdx: 6,
    themeBody: 'wifi_wraith',
    archetype: 'alien',
    palette: { base: '#67e8f9', light: '#ecfeff', dark: '#155e75', accent: '#a78bfa', glow: '#22d3ee' },
  },
  cola_kraken: {
    emoji: '🥤',
    aura: '#7f1d1d',
    label: 'Cola kraken',
    colorIdx: 0,
    themeBody: 'water_bottle',
    archetype: 'alien',
    palette: { base: '#6f1d1b', light: '#d9480f', dark: '#2f0e0d', accent: '#f8fafc', glow: '#fb7185' },
  },
  charging_cable_serpent: {
    emoji: '🔌',
    aura: '#facc15',
    label: 'Cable serpent',
    colorIdx: 6,
    themeBody: 'cable_serpent',
    archetype: 'mech',
    palette: { base: '#64748b', light: '#cbd5e1', dark: '#1f2937', accent: '#facc15', glow: '#fde047' },
  },
  algorithm_angel: {
    emoji: '👼',
    aura: '#fef3c7',
    label: 'AI angel',
    colorIdx: 2,
    themeBody: 'tablet',
    archetype: 'hybrid',
    palette: { base: '#e0f2fe', light: '#ffffff', dark: '#38bdf8', accent: '#facc15', glow: '#fde68a' },
  },
  trash_panda_ronin: {
    emoji: '🦝',
    aura: '#6b7280',
    label: 'Trash ronin',
    colorIdx: 5,
    themeBody: 'schoolbag',
    archetype: 'alien',
    palette: { base: '#4b5563', light: '#9ca3af', dark: '#1f2937', accent: '#94a3b8', glow: '#facc15' },
  },
  pizza_meteor: {
    emoji: '🍕',
    aura: '#fb923c',
    label: 'Pizza meteor',
    colorIdx: 5,
    themeBody: 'pizza_meteor',
    archetype: 'kaiju',
    palette: { base: '#f97316', light: '#fed7aa', dark: '#9a3412', accent: '#dc2626', glow: '#facc15' },
  },
  cloud_catfish: {
    emoji: '☁️',
    aura: '#bae6fd',
    label: 'Cloud catfish',
    colorIdx: 6,
    themeBody: 'water_bottle',
    archetype: 'hybrid',
    palette: { base: '#bae6fd', light: '#f0f9ff', dark: '#38bdf8', accent: '#64748b', glow: '#7dd3fc' },
  },
  keyboard_golem: {
    emoji: '⌨️',
    aura: '#94a3b8',
    label: 'Keyboard golem',
    colorIdx: 4,
    themeBody: 'homework',
    archetype: 'mech',
    palette: { base: '#475569', light: '#cbd5e1', dark: '#0f172a', accent: '#e2e8f0', glow: '#a5b4fc' },
  },
  noodle_basilisk: {
    emoji: '🍜',
    aura: '#f97316',
    label: 'Noodle basilisk',
    colorIdx: 5,
    themeBody: 'cable_serpent',
    archetype: 'alien',
    palette: { base: '#f59e0b', light: '#fde68a', dark: '#92400e', accent: '#ef4444', glow: '#fb923c' },
  },
  sneaker_shark: {
    emoji: '👟',
    aura: '#38bdf8',
    label: 'Sneaker shark',
    colorIdx: 6,
    themeBody: 'pencil',
    archetype: 'kaiju',
    palette: { base: '#38bdf8', light: '#bae6fd', dark: '#075985', accent: '#f8fafc', glow: '#67e8f9' },
  },
  battery_bat: {
    emoji: '🔋',
    aura: '#bef264',
    label: 'Battery bat',
    colorIdx: 3,
    themeBody: 'iphone',
    archetype: 'mech',
    palette: { base: '#365314', light: '#bef264', dark: '#1a2e05', accent: '#84cc16', glow: '#d9f99d' },
  },
  meme_monk: {
    emoji: '😂',
    aura: '#f9a8d4',
    label: 'Meme monk',
    colorIdx: 7,
    themeBody: 'sixtyseven',
    archetype: 'alien',
    palette: { base: '#f472b6', light: '#fbcfe8', dark: '#9d174d', accent: '#facc15', glow: '#f9a8d4' },
  },
  ice_cream_yeti: {
    emoji: '🍦',
    aura: '#e0f2fe',
    label: 'Ice cream yeti',
    colorIdx: 6,
    themeBody: 'chicken',
    archetype: 'kaiju',
    palette: { base: '#bfdbfe', light: '#ffffff', dark: '#60a5fa', accent: '#f9a8d4', glow: '#dbeafe' },
  },
  microwave_mantis: {
    emoji: '🔥',
    aura: '#fb7185',
    label: 'Microwave mantis',
    colorIdx: 0,
    themeBody: 'iphone',
    archetype: 'mech',
    palette: { base: '#ef4444', light: '#fca5a5', dark: '#7f1d1d', accent: '#facc15', glow: '#fb7185' },
  },
  traffic_cone_cyclops: {
    emoji: '🚧',
    aura: '#fb923c',
    label: 'Cone cyclops',
    colorIdx: 5,
    themeBody: 'toilet_paper',
    archetype: 'kaiju',
    palette: { base: '#f97316', light: '#fdba74', dark: '#9a3412', accent: '#ffffff', glow: '#fed7aa' },
  },
  bubblewrap_blob: {
    emoji: '🫧',
    aura: '#cffafe',
    label: 'Bubblewrap blob',
    colorIdx: 6,
    themeBody: 'poop',
    archetype: 'alien',
    palette: { base: '#a5f3fc', light: '#ecfeff', dark: '#22d3ee', accent: '#ffffff', glow: '#cffafe' },
  },
  drone_goblin: {
    emoji: '🛸',
    aura: '#93c5fd',
    label: 'Drone goblin',
    colorIdx: 6,
    themeBody: 'crocs',
    archetype: 'alien',
    palette: { base: '#2563eb', light: '#93c5fd', dark: '#1e3a8a', accent: '#facc15', glow: '#bfdbfe' },
  },
  blackout_bunny: {
    emoji: '⚡',
    aura: '#a78bfa',
    label: 'Blackout bunny',
    colorIdx: 4,
    themeBody: 'chicken',
    archetype: 'alien',
    palette: { base: '#312e81', light: '#a78bfa', dark: '#111827', accent: '#f472b6', glow: '#c084fc' },
  },
  core_feed_beast: {
    emoji: '🧿',
    aura: '#c084fc',
    label: 'Core feed beast',
    colorIdx: 4,
    themeBody: 'trex',
    archetype: 'kaiju',
    palette: { base: '#4c1d95', light: '#c084fc', dark: '#111827', accent: '#22d3ee', glow: '#e879f9' },
  },
};

export function getMonsterTheme(templateId) {
  return (
    MONSTER_THEMES[templateId] ?? {
      emoji: '👾',
      aura: '#a29bfe',
      label: 'Monster',
      themeBody: null,
      archetype: 'kaiju',
      palette: { base: '#a29bfe', light: '#dfe6e9', dark: '#6c5ce7', accent: '#fdcb6e', glow: '#ffeaa7' },
    }
  );
}

/** Merge theme into monster parts for previews and battle. */
export function applyMonsterTheme(templateId, parts, templateMeta = null) {
  const theme = getMonsterTheme(templateId);
  const base = parts && typeof parts === 'object' ? { ...parts } : {};
  const rarity = templateMeta?.rarity ?? base.rarity ?? null;
  return {
    ...base,
    templateId,
    rarity,
    themeEmoji: theme.emoji,
    themeAura: theme.aura,
    themeLabel: theme.label,
    themeBody: theme.themeBody ?? null,
    themeArchetype: theme.archetype ?? 'kaiju',
    themePalette: theme.palette ?? null,
    colorIdx: theme.colorIdx ?? base.colorIdx ?? 0,
  };
}
