/**
 * Monster roster: pricing, rarity, roles, combat bases & growth hints.
 * Visual evolution cues drive MonsterPreview / MoveEffect polish — tune freely.
 */

/** @typedef {'common'|'rare'|'epic'|'legendary'|'mythic'|'ultra_mythic'} MonsterRarity */
/** @typedef {'speedster'|'tank'|'brawler'|'mage'|'healer'|'support'|'trickster'|'balanced'|'mythic'|'tank_mage'} MonsterRole */

export const RARITY_ORDER = /** @type {const} */ (['common', 'rare', 'epic', 'legendary', 'mythic', 'ultra_mythic']);

/** @param {string} r */
export function rarityRank(r) {
  const i = RARITY_ORDER.indexOf(r);
  return i < 0 ? 0 : i;
}

export const RARITY_UI = {
  common: { label: 'Common', chipBg: '#dfe6e9', chipFg: '#2d3436', border: '#b2bec3' },
  rare: { label: 'Rare', chipBg: '#74b9ff', chipFg: '#1e3799', border: '#0984e3' },
  epic: { label: 'Epic', chipBg: '#a29bfe', chipFg: '#2d1b69', border: '#6c5ce7' },
  legendary: { label: 'Legendary', chipBg: '#ffeaa7', chipFg: '#d35400', border: '#fdcb6e' },
  mythic: { label: 'Mythic', chipBg: '#fd79a8', chipFg: '#6c1339', border: '#e84393' },
  ultra_mythic: { label: 'Ultra Mythic', chipBg: '#f1c40f', chipFg: '#5c4a00', border: '#d4ac0d' },
};

export const ROLE_LABELS = {
  speedster: 'Speedster',
  tank: 'Tank',
  brawler: 'Brawler',
  mage: 'Mage',
  healer: 'Healer',
  support: 'Support',
  trickster: 'Trickster',
  balanced: 'Balanced',
  mythic: 'Mythic',
  tank_mage: 'Tank · Mage',
};

/**
 * @typedef {{
 *   id: string,
 *   name: string,
 *   price: number,
 *   rarity: MonsterRarity,
 *   role: MonsterRole,
 *   description: string,
 *   baseStats: Record<string, number>,
 *   growthProfile: Record<string, number>,
 *   visualProfile: {
 *     defaultParts: Record<string, unknown>,
 *     auraColor?: string,
 *     evolutionIdeas?: string[],
 *     moveFlair?: string,
 *   },
 * }} MonsterTemplate
 */

/** @type {MonsterTemplate[]} */
export const MONSTER_CATALOG = [
  {
    id: 'cockroachsaurus',
    name: 'Cockroachsaurus',
    price: 15,
    rarity: 'common',
    role: 'speedster',
    description: 'Cheap but annoying. Dodges like mad.',
    baseStats: {
      hp: 130,
      mp: 50,
      attackMin: 13,
      attackMax: 18,
      magicMin: 8,
      magicMax: 14,
      defMin: 4,
      defMax: 8,
      magicDefMin: 4,
      magicDefMax: 8,
      critical: 10,
      dodge: 20,
    },
    growthProfile: {
      hpPerLevel: 3,
      mpPerLevel: 0.9,
      attackEveryLevels: 4,
      magicEveryLevels: 4,
      defEveryLevels: 6,
      magicDefEveryLevels: 6,
      criticalEveryLevels: 5,
      dodgeEveryLevels: 4,
    },
    visualProfile: {
      defaultParts: { species: 2, body: 1, head: 2, eyes: 3, mouth: 2, horn: 2, tail: 3, hands: 2, legs: 1, colorIdx: 5 },
      auraColor: '#636e72',
      evolutionIdeas: ['Wings sprout', 'Extra legs twitch', 'Shell gleams chrome'],
      moveFlair: 'critGlow',
    },
  },
  {
    id: 'chickenzilla',
    name: 'Chickenzilla',
    price: 25,
    rarity: 'common',
    role: 'brawler',
    description: 'Beginner beast — pecks hard and learns fast.',
    baseStats: {
      hp: 150,
      mp: 55,
      attackMin: 14,
      attackMax: 20,
      magicMin: 10,
      magicMax: 16,
      defMin: 6,
      defMax: 10,
      magicDefMin: 5,
      magicDefMax: 9,
      critical: 8,
      dodge: 12,
    },
    growthProfile: {
      hpPerLevel: 4,
      mpPerLevel: 1,
      attackEveryLevels: 4,
      magicEveryLevels: 4,
      defEveryLevels: 5,
      magicDefEveryLevels: 5,
      criticalEveryLevels: 7,
      dodgeEveryLevels: 7,
    },
    visualProfile: {
      defaultParts: { species: 0, body: 2, head: 3, eyes: 2, mouth: 2, horn: 3, tail: 1, hands: 2, legs: 2, colorIdx: 3 },
      auraColor: '#f39c12',
      evolutionIdeas: ['Comb grows fierce', 'Angry eyebrows ink in', 'Chicken armour plates'],
      moveFlair: 'foodSpark',
    },
  },
  {
    id: 'water_bottle_beast',
    name: 'Water Bottle Beast',
    price: 40,
    rarity: 'common',
    role: 'tank',
    description: 'Slosh tank — absorbs hits with soggy swagger.',
    baseStats: {
      hp: 170,
      mp: 60,
      attackMin: 12,
      attackMax: 18,
      magicMin: 12,
      magicMax: 18,
      defMin: 8,
      defMax: 14,
      magicDefMin: 7,
      magicDefMax: 13,
      critical: 6,
      dodge: 8,
    },
    growthProfile: {
      hpPerLevel: 6,
      mpPerLevel: 1.2,
      attackEveryLevels: 5,
      magicEveryLevels: 5,
      defEveryLevels: 4,
      magicDefEveryLevels: 4,
      criticalEveryLevels: 9,
      dodgeEveryLevels: 9,
    },
    visualProfile: {
      defaultParts: { species: 1, body: 3, head: 1, eyes: 1, mouth: 1, horn: 0, tail: 2, hands: 1, legs: 3, colorIdx: 3 },
      auraColor: '#48cae4',
      evolutionIdeas: ['Water aura ripples', 'Bottle torso expands', 'Splash particle halo'],
      moveFlair: 'waterBurst',
    },
  },
  {
    id: 'crocs_goblin',
    name: 'Crocs Goblin',
    price: 60,
    rarity: 'rare',
    role: 'speedster',
    description: 'Riverbank nuisance — blink and it dodged.',
    baseStats: {
      hp: 145,
      mp: 65,
      attackMin: 15,
      attackMax: 22,
      magicMin: 10,
      magicMax: 16,
      defMin: 5,
      defMax: 10,
      magicDefMin: 5,
      magicDefMax: 10,
      critical: 12,
      dodge: 22,
    },
    growthProfile: {
      hpPerLevel: 4,
      mpPerLevel: 1.3,
      attackEveryLevels: 4,
      magicEveryLevels: 5,
      defEveryLevels: 6,
      magicDefEveryLevels: 6,
      criticalEveryLevels: 5,
      dodgeEveryLevels: 4,
    },
    visualProfile: {
      defaultParts: { species: 3, body: 2, head: 2, eyes: 4, mouth: 3, horn: 1, tail: 1, hands: 3, legs: 2, colorIdx: 6 },
      auraColor: '#00cec9',
      evolutionIdeas: ['Oversized Crocs slap ground', 'Speed trail streak', 'Hop dodge flourish'],
      moveFlair: 'speedTrail',
    },
  },
  {
    id: 'iphone_warrior',
    name: 'iPhone Warrior',
    price: 90,
    rarity: 'rare',
    role: 'tank',
    description: 'Glass cannon armour — shocks foes.',
    baseStats: {
      hp: 165,
      mp: 75,
      attackMin: 14,
      attackMax: 20,
      magicMin: 16,
      magicMax: 23,
      defMin: 7,
      defMax: 12,
      magicDefMin: 10,
      magicDefMax: 16,
      critical: 8,
      dodge: 10,
    },
    growthProfile: {
      hpPerLevel: 5,
      mpPerLevel: 1.8,
      attackEveryLevels: 5,
      magicEveryLevels: 4,
      defEveryLevels: 4,
      magicDefEveryLevels: 4,
      criticalEveryLevels: 7,
      dodgeEveryLevels: 8,
    },
    visualProfile: {
      defaultParts: { species: 3, body: 3, head: 1, eyes: 2, mouth: 2, horn: 0, tail: 0, hands: 2, legs: 3, colorIdx: 4 },
      auraColor: '#dfe6e9',
      evolutionIdeas: ['Polished chassis gleam', 'Floating screen shield', 'Lightning charge arcs'],
      moveFlair: 'lightningArc',
    },
  },
  {
    id: 'lunchbox_dragon',
    name: 'Lunchbox Dragon',
    price: 80,
    rarity: 'rare',
    role: 'mage',
    description: 'Snack hoarder — casts spicy lunch magic.',
    baseStats: {
      hp: 160,
      mp: 70,
      attackMin: 15,
      attackMax: 21,
      magicMin: 14,
      magicMax: 21,
      defMin: 7,
      defMax: 12,
      magicDefMin: 7,
      magicDefMax: 12,
      critical: 9,
      dodge: 12,
    },
    growthProfile: {
      hpPerLevel: 5,
      mpPerLevel: 1.5,
      attackEveryLevels: 4,
      magicEveryLevels: 4,
      defEveryLevels: 5,
      magicDefEveryLevels: 5,
      criticalEveryLevels: 6,
      dodgeEveryLevels: 7,
    },
    visualProfile: {
      defaultParts: { species: 2, body: 2, head: 3, eyes: 2, mouth: 2, horn: 3, tail: 2, hands: 2, legs: 2, colorIdx: 2 },
      auraColor: '#ffeaa7',
      evolutionIdeas: ['Wings made of trays', 'Food aura crumbs', 'Sparkle snacks heal vibe'],
      moveFlair: 'foodSpark',
    },
  },
  {
    id: 'pencil_shark',
    name: 'Pencil Shark',
    price: 100,
    rarity: 'rare',
    role: 'brawler',
    description: 'Woodgrain predator — sharpened crits.',
    baseStats: {
      hp: 155,
      mp: 60,
      attackMin: 18,
      attackMax: 25,
      magicMin: 10,
      magicMax: 16,
      defMin: 6,
      defMax: 11,
      magicDefMin: 5,
      magicDefMax: 10,
      critical: 15,
      dodge: 13,
    },
    growthProfile: {
      hpPerLevel: 4,
      mpPerLevel: 1,
      attackEveryLevels: 3,
      magicEveryLevels: 5,
      defEveryLevels: 6,
      magicDefEveryLevels: 6,
      criticalEveryLevels: 4,
      dodgeEveryLevels: 6,
    },
    visualProfile: {
      defaultParts: { species: 2, body: 1, head: 2, eyes: 3, mouth: 3, horn: 2, tail: 3, hands: 3, legs: 1, colorIdx: 7 },
      auraColor: '#fab1a0',
      evolutionIdeas: ['Sharper graphite nose', 'Ink slash arcs', 'Crit violet flare'],
      moveFlair: 'critGlow',
    },
  },
  {
    id: 'homework_troll',
    name: 'Homework Troll',
    price: 120,
    rarity: 'epic',
    role: 'mage',
    description: 'Stacks spells like overdue worksheets.',
    baseStats: {
      hp: 160,
      mp: 90,
      attackMin: 12,
      attackMax: 18,
      magicMin: 20,
      magicMax: 28,
      defMin: 6,
      defMax: 11,
      magicDefMin: 9,
      magicDefMax: 15,
      critical: 10,
      dodge: 10,
    },
    growthProfile: {
      hpPerLevel: 4,
      mpPerLevel: 2.8,
      attackEveryLevels: 6,
      magicEveryLevels: 3,
      defEveryLevels: 6,
      magicDefEveryLevels: 5,
      criticalEveryLevels: 7,
      dodgeEveryLevels: 8,
    },
    visualProfile: {
      defaultParts: { species: 1, body: 2, head: 1, eyes: 4, mouth: 2, horn: 2, tail: 2, hands: 2, legs: 2, colorIdx: 1 },
      auraColor: '#a29bfe',
      evolutionIdeas: ['Floating worksheets whirl', 'Teacher glare halo', 'Magic chalk glyphs'],
      moveFlair: 'glyphBurst',
    },
  },
  {
    id: 'toilet_paper_ninja',
    name: 'Toilet Paper Ninja',
    price: 150,
    rarity: 'epic',
    role: 'trickster',
    description: 'Spin-to-win chaos — slippery dodges.',
    baseStats: {
      hp: 150,
      mp: 80,
      attackMin: 17,
      attackMax: 24,
      magicMin: 16,
      magicMax: 24,
      defMin: 6,
      defMax: 10,
      magicDefMin: 6,
      magicDefMax: 10,
      critical: 14,
      dodge: 24,
    },
    growthProfile: {
      hpPerLevel: 4,
      mpPerLevel: 2,
      attackEveryLevels: 4,
      magicEveryLevels: 4,
      defEveryLevels: 7,
      magicDefEveryLevels: 7,
      criticalEveryLevels: 5,
      dodgeEveryLevels: 4,
    },
    visualProfile: {
      defaultParts: { species: 3, body: 1, head: 2, eyes: 3, mouth: 2, horn: 0, tail: 3, hands: 3, legs: 2, colorIdx: 0 },
      auraColor: '#dfe6e9',
      evolutionIdeas: ['Longer TP scarf trails', 'Whirlwind spins faster', 'Smoke puff escapes'],
      moveFlair: 'smokeBurst',
    },
  },
  {
    id: 'schoolbag_golem',
    name: 'Schoolbag Golem',
    price: 180,
    rarity: 'epic',
    role: 'tank',
    description: 'Heavy backpack brute — stompy defence.',
    baseStats: {
      hp: 210,
      mp: 65,
      attackMin: 17,
      attackMax: 24,
      magicMin: 10,
      magicMax: 16,
      defMin: 12,
      defMax: 18,
      magicDefMin: 9,
      magicDefMax: 15,
      critical: 6,
      dodge: 6,
    },
    growthProfile: {
      hpPerLevel: 7,
      mpPerLevel: 1.2,
      attackEveryLevels: 4,
      magicEveryLevels: 5,
      defEveryLevels: 4,
      magicDefEveryLevels: 4,
      criticalEveryLevels: 10,
      dodgeEveryLevels: 11,
    },
    visualProfile: {
      defaultParts: { species: 3, body: 3, head: 1, eyes: 1, mouth: 1, horn: 1, tail: 0, hands: 2, legs: 3, colorIdx: 4 },
      auraColor: '#b2bec3',
      evolutionIdeas: ['Armour straps thicken', 'Heavier stomp shockwave', 'Chalk dust clouds'],
      moveFlair: 'dustWave',
    },
  },
  {
    id: 't_rex',
    name: 'T-Rex',
    price: 220,
    rarity: 'legendary',
    role: 'brawler',
    description: 'Big teeth. Big damage. Small patience.',
    baseStats: {
      hp: 220,
      mp: 70,
      attackMin: 24,
      attackMax: 34,
      magicMin: 10,
      magicMax: 18,
      defMin: 10,
      defMax: 16,
      magicDefMin: 7,
      magicDefMax: 13,
      critical: 11,
      dodge: 7,
    },
    growthProfile: {
      hpPerLevel: 6,
      mpPerLevel: 1.4,
      attackEveryLevels: 3,
      magicEveryLevels: 6,
      defEveryLevels: 5,
      magicDefEveryLevels: 5,
      criticalEveryLevels: 6,
      dodgeEveryLevels: 9,
    },
    visualProfile: {
      defaultParts: { species: 2, body: 3, head: 3, eyes: 3, mouth: 4, horn: 1, tail: 3, hands: 2, legs: 2, colorIdx: 5 },
      auraColor: '#e17055',
      evolutionIdeas: ['Teeth rows widen', 'Tail spikes ignite', 'Roar shock aura'],
      moveFlair: 'roarBurst',
    },
  },
  {
    id: 'tablet_wizard',
    name: 'Tablet Wizard',
    price: 250,
    rarity: 'legendary',
    role: 'support',
    description: 'Legendary support — buy in the Monster Mart. Wellness apps heal the team; Restore Ritual revives fallen allies.',
    baseStats: {
      hp: 182,
      mp: 108,
      attackMin: 12,
      attackMax: 17,
      magicMin: 20,
      magicMax: 30,
      defMin: 9,
      defMax: 13,
      magicDefMin: 13,
      magicDefMax: 19,
      critical: 9,
      dodge: 9,
    },
    growthProfile: {
      hpPerLevel: 4,
      mpPerLevel: 3.5,
      attackEveryLevels: 7,
      magicEveryLevels: 3,
      defEveryLevels: 6,
      magicDefEveryLevels: 4,
      criticalEveryLevels: 6,
      dodgeEveryLevels: 8,
    },
    visualProfile: {
      defaultParts: { species: 3, body: 2, head: 2, eyes: 2, mouth: 2, horn: 0, tail: 1, hands: 3, legs: 2, colorIdx: 6 },
      auraColor: '#81ecec',
      evolutionIdeas: ['Floating tablet orbit', 'Healing glyph pulse', 'Restore aura glow'],
      moveFlair: 'healPulse',
    },
  },
  {
    id: 'skibidi_bot',
    name: 'Skibidi-Bot',
    price: 300,
    rarity: 'legendary',
    role: 'trickster',
    description: 'Camera-headed chaos gremlin.',
    baseStats: {
      hp: 190,
      mp: 105,
      attackMin: 18,
      attackMax: 27,
      magicMin: 24,
      magicMax: 34,
      defMin: 9,
      defMax: 15,
      magicDefMin: 10,
      magicDefMax: 17,
      critical: 13,
      dodge: 16,
    },
    growthProfile: {
      hpPerLevel: 5,
      mpPerLevel: 2.6,
      attackEveryLevels: 4,
      magicEveryLevels: 4,
      defEveryLevels: 5,
      magicDefEveryLevels: 5,
      criticalEveryLevels: 5,
      dodgeEveryLevels: 6,
    },
    visualProfile: {
      defaultParts: { species: 3, body: 1, head: 1, eyes: 4, mouth: 4, horn: 2, tail: 2, hands: 3, legs: 2, colorIdx: 5 },
      auraColor: '#636e72',
      evolutionIdeas: ['LED strobes flare', 'Toilet rocket trails', 'Glitch jitter aura'],
      moveFlair: 'glitchPulse',
    },
  },
  {
    id: 'bubble_tea_slime',
    name: 'Bubble Tea Slime',
    price: 500,
    rarity: 'mythic',
    role: 'tank',
    description: 'Mythic pearl fortress — Earth / Water. Counters 67-Rex.',
    baseStats: {
      hp: 292,
      mp: 108,
      attackMin: 14,
      attackMax: 20,
      magicMin: 18,
      magicMax: 26,
      defMin: 19,
      defMax: 26,
      magicDefMin: 18,
      magicDefMax: 25,
      critical: 6,
      dodge: 7,
    },
    growthProfile: {
      hpPerLevel: 9,
      mpPerLevel: 2.8,
      attackEveryLevels: 6,
      magicEveryLevels: 5,
      defEveryLevels: 3,
      magicDefEveryLevels: 3,
      criticalEveryLevels: 9,
      dodgeEveryLevels: 10,
    },
    visualProfile: {
      defaultParts: { species: 1, body: 3, head: 2, eyes: 2, mouth: 2, horn: 0, tail: 2, hands: 2, legs: 2, colorIdx: 2 },
      auraColor: '#fd79a8',
      evolutionIdeas: ['Pearls orbit wider', 'Bouncier slime silhouette', 'Bubble aura dome'],
      moveFlair: 'bubblePop',
    },
  },
  {
    id: 'sixtyseven_rex',
    name: '67-Rex',
    price: 500,
    rarity: 'mythic',
    role: 'brawler',
    description: 'Mythic physical bruiser — Metal / Fire. Counters Core Feed Beast.',
    baseStats: {
      hp: 252,
      mp: 118,
      attackMin: 34,
      attackMax: 46,
      magicMin: 14,
      magicMax: 22,
      defMin: 15,
      defMax: 21,
      magicDefMin: 12,
      magicDefMax: 18,
      critical: 18,
      dodge: 10,
    },
    growthProfile: {
      hpPerLevel: 7,
      mpPerLevel: 3,
      attackEveryLevels: 2,
      magicEveryLevels: 6,
      defEveryLevels: 4,
      magicDefEveryLevels: 5,
      criticalEveryLevels: 4,
      dodgeEveryLevels: 8,
    },
    visualProfile: {
      defaultParts: { species: 2, body: 3, head: 3, eyes: 4, mouth: 4, horn: 3, tail: 3, hands: 3, legs: 2, colorIdx: 4 },
      auraColor: '#f1c40f',
      evolutionIdeas: ['“67” glyph burns bright', 'Golden aura pillar', 'Roar summons mythic lightning'],
      moveFlair: 'mythicStrike',
    },
  },
  {
    id: 'goldzilla',
    name: 'Goldzilla',
    price: 500,
    rarity: 'ultra_mythic',
    role: 'balanced',
    description: 'Ultra Mythic all-rounder — Metal / Earth. ~10% stronger than other mythics. Counters Algorithm Angel.',
    baseStats: {
      hp: 295,
      mp: 141,
      attackMin: 29,
      attackMax: 37,
      magicMin: 29,
      magicMax: 37,
      defMin: 19,
      defMax: 25,
      magicDefMin: 19,
      magicDefMax: 25,
      critical: 14,
      dodge: 12,
    },
    growthProfile: {
      hpPerLevel: 7.5,
      mpPerLevel: 3.5,
      attackEveryLevels: 3,
      magicEveryLevels: 3,
      defEveryLevels: 3,
      magicDefEveryLevels: 3,
      criticalEveryLevels: 5,
      dodgeEveryLevels: 7,
    },
    visualProfile: {
      defaultParts: { species: 2, body: 3, head: 3, eyes: 4, mouth: 4, horn: 3, tail: 3, hands: 3, legs: 2, colorIdx: 4 },
      auraColor: '#f1c40f',
      evolutionIdeas: ['Gold plating thickens', 'Executive aura flare', 'Billionaire roar shakes the arena'],
      moveFlair: 'mythicStrike',
    },
  },
];

/** @type {Record<string, MonsterTemplate>} */
export const MONSTER_BY_ID = Object.fromEntries(MONSTER_CATALOG.map((m) => [m.id, m]));

/** @param {string} id */
export function getMonsterTemplate(id) {
  return MONSTER_BY_ID[id] ?? null;
}
